# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterusage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10meterusage.proto\x12\x07\x65xample\"\x16\n\x14GetMeterUsageRequest\"!\n\nMeterUsage\x12\x13\n\x0b\x63sv_content\x18\x01 \x01(\t2Z\n\x11MeterUsageService\x12\x45\n\rGetMeterUsage\x12\x1d.example.GetMeterUsageRequest\x1a\x13.example.MeterUsage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meterusage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETMETERUSAGEREQUEST']._serialized_start=29
  _globals['_GETMETERUSAGEREQUEST']._serialized_end=51
  _globals['_METERUSAGE']._serialized_start=53
  _globals['_METERUSAGE']._serialized_end=86
  _globals['_METERUSAGESERVICE']._serialized_start=88
  _globals['_METERUSAGESERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
